steps:
  # Build DexScreener image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.dexscreener', '-t', 'gcr.io/$PROJECT_ID/dexscreener-crawler', '.']

  # Build DexPaprika image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.dexpaprika', '-t', 'gcr.io/$PROJECT_ID/dexpaprika-crawler', '.']

images:
  - 'gcr.io/$PROJECT_ID/dexscreener-crawler'
  - 'gcr.io/$PROJECT_ID/dexpaprika-crawler'
