version: '3.9'
services:
  degen-digest:
    build: .
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    command: python main.py
    restart: unless-stopped

  cron-schedule:
    build: .
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    command: ["crond", "-f", "-L", "/app/logs/cron.log"]
    restart: unless-stopped 