#!/usr/bin/env python3
"""
Influencers configuration for enhanced viral prediction with Solana focus
"""


def get_influencers():
    """Get list of crypto influencers to monitor with Solana focus"""
    return [
        # Solana-focused influencers (high priority)
        "solana",
        "solanalabs",
        "phantom",
        "solflare",
        "raydium",
        "orca_protocol",
        "jupiter",
        "serumdex",
        "mango_markets",
        "saber_hq",
        "metaplex",
        "magiceden",
        "bonk_inu",
        "dogwifhat",
        "bookofmeme",
        "popcat",
        "jup_ag",
        "raydium_io",
        "orca_so",
        "mango_markets",
        "serum_project",
        "saber_hq",
        "solana_fndn",
        "solana_status",
        "solana_break",
        "solana_news",
        "solana_daily",
        "solana_insider",
        "solana_alpha",
        "solana_whale",
        "solana_trader",
        "solana_analyst",
        "solana_guru",
        "solana_master",
        "solana_king",
        "solana_queen",
        "solana_bull",
        "solana_moon",
        "solana_pump",
        "solana_airdrop",
        "solana_launch",
        "solana_rug",
        "solana_scam",
        "solana_fud",
        "solana_fomo",
        # Solana ecosystem developers and founders
        "rajgokal",
        "toly",
        "anatoly",
        "sbf",
        "sam_bankman",
        "sbf_ftx",
        "sbf_alameda",
        "caroline_ellison",
        "gary_wang",
        "nishad_singh",
        "tom_brady",
        "gisele",
        # General crypto influencers (maintain market pulse)
        "CryptoCobain",
        "CryptoKaleo",
        "0xfoobar",
        "ansem",
        "sisyphus",
        "degendata",
        "DegenSpartan",
        "WassieCapital",
        "gcrclassic",
        "punk9059",
        "punk6529",
        "SatoshiLite",
        "TheCryptoDog",
        "Cobie",
        "CryptoDonAlt",
        "Gainzy222",
        "AltcoinPsycho",
        "degenharambe",
        "dilutionproof",
        "rektbuilder",
        "redphonecrypto",
        "inversebrah",
        "route2fi",
        "du5tm",
        "mayne",
        "lightcrypto",
        "imnotartsy",
        "LedgerStatus",
        "martiniGuyYT",
        "Pentosh1",
        "TraderSZ",
        "CryptoCred",
        "BitcoinMagazine",
        "hype_eth",
        "loopifyyy",
        "RaoulGMI",
        "elonmusk",
        "cz_binance",
        "VitalikButerin",
        "APompliano",
        "balajis",
        "aantonop",
        "CryptoWendyO",
        "TheMoonCarl",
        "Melt_Dem",
        "DTAPCAP",
        "CamilaRusso",
        "IvanOnTech",
        "chrisdixon",
        "WhalePanda",
        "saylor",
        "ErikVoorhees",
        "naval",
        "TheCryptoLark",
        "bitboy_crypto",
        "intocryptoverse",
        "TySmithHQ",
        "MMCrypto",
        "AshCrypto",
        "CryptoRover",
        "PlanB",
        "WClementeIII",
        "ChrisJaszczyns",
        "CryptoMichNL",
        "ilCapoOfCrypto",
        "ChrisOG",
        "ERVA",
        "cdixon",
        "CathieDWood",
        "DasAbhyudoy",
        "sandeepnailwal",
        "adam3us",
        "justinsuntron",
        "CharlesHoskinson",
        "laurashin",
        "CryptoGokhshtein",
        "MissTeenCrypto",
        "GirlGoneCrypto",
        "CryptoTony",
        "Cred",
        "CryptoELlTES",
        "STEPHISCRYPTO",
        "TitanOfCrypto",
        "OTC_Bitcoin",
        "CryptoRaven",
        "CryptoDeus",
        "CryptoBrekkie",
        "ScottMelker",
        "ToneVays",
        "rogerkver",
        "pmarca",
        "paulg",
        "lopp",
        "DTAPCAP",
        "woonomic",
        "BenjaminCowen",
        "Trader_Jibon",
        "cryptocevo",
        "loomdart",
        "KoroushAK",
        "AltcoinGordon",
        "Trader_XO",
        "CryptoWizardd",
        "TraderMayne",
    ]


def get_influencer_categories():
    """Get influencers categorized by type with Solana focus"""
    return {
        "solana_core": [
            "solana",
            "solanalabs",
            "solana_fndn",
            "solana_status",
            "rajgokal",
            "toly",
            "anatoly",
            "sbf",
            "sam_bankman",
            "sbf_ftx",
            "sbf_alameda",
            "caroline_ellison",
            "gary_wang",
            "nishad_singh",
        ],
        "solana_ecosystem": [
            "phantom",
            "solflare",
            "raydium",
            "orca_protocol",
            "jupiter",
            "serumdex",
            "mango_markets",
            "saber_hq",
            "metaplex",
            "magiceden",
            "raydium_io",
            "orca_so",
            "serum_project",
            "saber_hq",
        ],
        "solana_tokens": [
            "bonk_inu",
            "dogwifhat",
            "bookofmeme",
            "popcat",
            "jup_ag",
            "raydium_io",
            "orca_so",
            "mango_markets",
            "serum_project",
            "saber_hq",
        ],
        "solana_community": [
            "solana_break",
            "solana_news",
            "solana_daily",
            "solana_insider",
            "solana_alpha",
            "solana_whale",
            "solana_trader",
            "solana_analyst",
            "solana_guru",
            "solana_master",
            "solana_king",
            "solana_queen",
            "solana_bull",
            "solana_moon",
            "solana_pump",
            "solana_airdrop",
            "solana_launch",
            "solana_rug",
            "solana_scam",
            "solana_fud",
            "solana_fomo",
        ],
        "traders": [
            "CryptoCobain",
            "CryptoKaleo",
            "CryptoDonAlt",
            "Gainzy222",
            "AltcoinPsycho",
            "TraderSZ",
            "CryptoCred",
            "Trader_Jibon",
            "Trader_XO",
            "TraderMayne",
        ],
        "analysts": [
            "0xfoobar",
            "ansem",
            "sisyphus",
            "degendata",
            "DegenSpartan",
            "Cobie",
            "PlanB",
            "WClementeIII",
            "BenjaminCowen",
            "AltcoinGordon",
        ],
        "founders": [
            "VitalikButerin",
            "cz_binance",
            "saylor",
            "justinsuntron",
            "CharlesHoskinson",
            "sandeepnailwal",
            "adam3us",
        ],
        "media": [
            "BitcoinMagazine",
            "CryptoWendyO",
            "CamilaRusso",
            "IvanOnTech",
            "TheCryptoLark",
            "CryptoMichNL",
            "CryptoBrekkie",
        ],
        "influencers": [
            "elonmusk",
            "APompliano",
            "balajis",
            "aantonop",
            "chrisdixon",
            "cdixon",
            "CathieDWood",
            "laurashin",
            "pmarca",
            "paulg",
        ],
    }


def get_high_priority_influencers():
    """Get high-priority influencers for real-time monitoring with Solana focus"""
    return [
        # Solana high priority
        "solana",
        "solanalabs",
        "phantom",
        "raydium",
        "orca_protocol",
        "jupiter",
        "bonk_inu",
        "dogwifhat",
        "bookofmeme",
        "rajgokal",
        "toly",
        "anatoly",
        "solana_fndn",
        "solana_status",
        "solana_break",
        "solana_news",
        # General high priority
        "CryptoCobain",
        "CryptoKaleo",
        "Cobie",
        "VitalikButerin",
        "cz_binance",
        "elonmusk",
        "saylor",
        "PlanB",
        "BenjaminCowen",
    ]


def get_solana_specific_influencers():
    """Get Solana-specific influencers for focused monitoring"""
    return [
        # Core Solana
        "solana",
        "solanalabs",
        "solana_fndn",
        "solana_status",
        "rajgokal",
        "toly",
        "anatoly",
        # Ecosystem
        "phantom",
        "solflare",
        "raydium",
        "orca_protocol",
        "jupiter",
        "serumdex",
        "mango_markets",
        "saber_hq",
        "metaplex",
        "magiceden",
        # Popular tokens
        "bonk_inu",
        "dogwifhat",
        "bookofmeme",
        "popcat",
        "jup_ag",
        "raydium_io",
        "orca_so",
        "mango_markets",
        "serum_project",
        "saber_hq",
        # Community
        "solana_break",
        "solana_news",
        "solana_daily",
        "solana_insider",
        "solana_alpha",
        "solana_whale",
        "solana_trader",
        "solana_analyst",
        "solana_guru",
        "solana_master",
        "solana_king",
        "solana_queen",
        "solana_bull",
        "solana_moon",
        "solana_pump",
        "solana_airdrop",
        "solana_launch",
        "solana_rug",
        "solana_scam",
        "solana_fud",
        "solana_fomo",
    ]
