#!/usr/bin/env python3
"""
Keywords configuration for enhanced viral prediction with Solana focus
"""


def get_keywords():
    """Get keywords for different platforms with Solana focus"""
    return {
        "twitter_search": [
            # Solana-specific keywords (high priority)
            "solana",
            "sol",
            "$sol",
            "saga",
            "phantom",
            "solflare",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "saber",
            "spl",
            "spl token",
            "metaplex",
            "candy machine",
            "magic eden",
            "opensea solana",
            "solana nft",
            "solana defi",
            "solana dex",
            "solana airdrop",
            "bonk",
            "$bonk",
            "dogwifhat",
            "wif",
            "$wif",
            "bome",
            "$bome",
            "popcat",
            "$popcat",
            "book of meme",
            "jup",
            "$jup",
            "ray",
            "$ray",
            "orca",
            "$orca",
            "mngo",
            "$mngo",
            "srm",
            "$srm",
            "sbr",
            "$sbr",
            "solana ecosystem",
            "solana season",
            "solana summer",
            "solana pump",
            "solana moon",
            "solana bull",
            "solana meme",
            "solana token",
            "solana launch",
            "solana rug",
            "solana scam",
            "solana airdrop",
            "solana presale",
            "solana ico",
            "solana ido",
            "solana fair launch",
            "solana stealth launch",
            # General crypto keywords (maintain market pulse)
            "rug",
            "airdrop",
            "new coin",
            "launched",
            "celebrity token",
            "pump",
            "0 tax",
            "moon",
            "bull",
            "bear",
            "dump",
            "scam",
            "honeypot",
            "free",
            "claim",
            "drop",
            "bitcoin",
            "ethereum",
            "btc",
            "eth",
            "defi",
            "nft",
            "meme",
            "altcoin",
            "crypto",
            "trading",
            "chart",
            "technical",
            "analysis",
            "news",
            "announcement",
            "update",
        ],
        "reddit": [
            # Solana-focused
            "solana",
            "sol",
            "phantom",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "bonk",
            "dogwifhat",
            "bome",
            "book of meme",
            "solana nft",
            "solana defi",
            "solana airdrop",
            "solana token",
            "solana launch",
            "solana ecosystem",
            # General crypto
            "rug",
            "airdrop",
            "scam",
            "launch",
            "meme coin",
            "celebrity",
            "pump",
            "dump",
            "bitcoin",
            "ethereum",
            "defi",
            "nft",
            "trading",
            "analysis",
            "news",
            "moon",
        ],
        "telegram": [
            # Solana-focused
            "solana",
            "sol",
            "phantom",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "bonk",
            "dogwifhat",
            "bome",
            "solana airdrop",
            "solana token",
            "solana launch",
            # General crypto
            "rug",
            "airdrop",
            "token",
            "launch",
            "whale",
            "pump",
            "dump",
            "scam",
            "free",
            "bitcoin",
            "ethereum",
            "defi",
            "nft",
            "meme",
            "altcoin",
            "crypto",
        ],
        "news": [
            # Solana-focused
            "solana",
            "solana blockchain",
            "solana foundation",
            "phantom wallet",
            "raydium",
            "jupiter aggregator",
            "serum dex",
            "mango markets",
            "bonk",
            "dogwifhat",
            "solana nft",
            "solana defi",
            "solana ecosystem",
            "solana adoption",
            # General crypto
            "cryptocurrency",
            "bitcoin",
            "ethereum",
            "blockchain",
            "defi",
            "nft",
            "crypto",
            "regulation",
            "adoption",
            "institutional",
            "investment",
            "trading",
            "market",
        ],
        "market": [
            # Solana-focused
            "solana",
            "sol",
            "phantom",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "bonk",
            "dogwifhat",
            "bome",
            "solana ecosystem",
            "solana tokens",
            # General crypto
            "bitcoin",
            "ethereum",
            "defi",
            "nft",
            "meme",
            "altcoin",
            "stablecoin",
            "exchange",
        ],
    }


def get_viral_keywords():
    """Get keywords that indicate potential virality with Solana focus"""
    return {
        "high_viral": [
            # Solana viral keywords
            "solana moon",
            "sol pump",
            "bonk moon",
            "wif moon",
            "bome moon",
            "solana season",
            "solana summer",
            "solana bull run",
            "phantom airdrop",
            "raydium airdrop",
            "jupiter airdrop",
            "solana airdrop",
            "solana launch",
            "solana stealth",
            "solana fair launch",
            "solana presale",
            "solana ico",
            "solana ido",
            # General viral keywords
            "moon",
            "pump",
            "bull",
            "rocket",
            "🚀",
            "💎",
            "diamond",
            "hodl",
            "lambo",
            "airdrop",
            "free",
            "claim",
            "drop",
            "launch",
            "new",
            "announcement",
        ],
        "medium_viral": [
            # Solana medium viral
            "solana",
            "sol",
            "phantom",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "bonk",
            "dogwifhat",
            "bome",
            "solana defi",
            "solana nft",
            "solana ecosystem",
            # General medium viral
            "bitcoin",
            "ethereum",
            "btc",
            "eth",
            "defi",
            "nft",
            "crypto",
            "trading",
            "analysis",
            "chart",
            "technical",
            "news",
            "update",
        ],
        "low_viral": [
            # Solana negative
            "solana rug",
            "solana scam",
            "solana dump",
            "solana bear",
            "solana dead",
            # General negative
            "bear",
            "dump",
            "sell",
            "short",
            "dead",
            "💀",
            "📉",
            "rekt",
            "scam",
            "rug",
        ],
        "trending_topics": [
            # Solana trending
            "solana season",
            "solana summer",
            "bonk season",
            "dogwifhat season",
            "solana ecosystem",
            "phantom wallet",
            "raydium dex",
            "jupiter aggregator",
            "solana nft boom",
            "solana defi summer",
            "solana meme season",
            # General trending
            "bitcoin etf",
            "ethereum merge",
            "defi summer",
            "nft boom",
            "meme season",
            "altcoin season",
            "bull run",
            "bear market",
            "crypto winter",
        ],
    }


def get_sentiment_keywords():
    """Get keywords for sentiment analysis with Solana focus"""
    return {
        "positive": [
            # Solana positive
            "solana moon",
            "sol pump",
            "bonk moon",
            "wif moon",
            "bome moon",
            "solana bull",
            "solana season",
            "solana summer",
            "phantom airdrop",
            "raydium airdrop",
            "jupiter airdrop",
            "solana airdrop",
            "solana launch",
            "solana ecosystem",
            # General positive
            "moon",
            "pump",
            "bull",
            "buy",
            "long",
            "hodl",
            "diamond",
            "rocket",
            "🚀",
            "💎",
            "lambo",
            "mooning",
            "pumping",
            "bullish",
            "bullrun",
            "moonboy",
            "diamond hands",
        ],
        "negative": [
            # Solana negative
            "solana rug",
            "solana scam",
            "solana dump",
            "solana bear",
            "solana dead",
            "solana honeypot",
            "solana ponzi",
            # General negative
            "dump",
            "bear",
            "sell",
            "short",
            "rug",
            "scam",
            "honeypot",
            "dead",
            "💀",
            "📉",
            "rekt",
            "dumpster",
            "bearish",
            "bear market",
            "paper hands",
            "fud",
        ],
        "fomo": [
            # Solana FOMO
            "solana moon",
            "sol pump",
            "bonk moon",
            "wif moon",
            "bome moon",
            "solana season",
            "solana airdrop",
            "phantom airdrop",
            "raydium airdrop",
            "jupiter airdrop",
            "solana launch",
            "solana stealth",
            "solana fair launch",
            "solana presale",
            "solana ico",
            "solana ido",
            "last chance solana",
            "don't miss solana",
            "solana going to moon",
            "next solana",
            "solana 100x",
            "solana 1000x",
            # General FOMO
            "moon",
            "pump",
            "rocket",
            "🚀",
            "mooning",
            "pumping",
            "fomo",
            "fear of missing out",
            "last chance",
            "don't miss",
            "going to moon",
            "next bitcoin",
        ],
        "fud": [
            # Solana FUD
            "solana scam",
            "solana rug",
            "solana honeypot",
            "solana dead",
            "solana ponzi",
            "solana bubble",
            "solana crash",
            "solana fud",
            "solana fear uncertainty doubt",
            # General FUD
            "scam",
            "rug",
            "honeypot",
            "dead",
            "💀",
            "dump",
            "bear",
            "sell",
            "fud",
            "fear uncertainty doubt",
            "ponzi",
            "bubble",
            "crash",
        ],
    }


def get_topic_keywords():
    """Get keywords for topic categorization with Solana focus"""
    return {
        "solana": [
            "solana",
            "sol",
            "$sol",
            "saga",
            "phantom",
            "solflare",
            "raydium",
            "orca",
            "jupiter",
            "serum",
            "mango",
            "saber",
            "spl",
            "spl token",
            "metaplex",
            "candy machine",
            "magic eden",
            "opensea solana",
            "solana nft",
            "solana defi",
            "solana dex",
            "solana airdrop",
            "bonk",
            "$bonk",
            "dogwifhat",
            "wif",
            "$wif",
            "bome",
            "$bome",
            "popcat",
            "$popcat",
            "book of meme",
            "jup",
            "$jup",
            "ray",
            "$ray",
            "orca",
            "$orca",
            "mngo",
            "$mngo",
            "srm",
            "$srm",
            "sbr",
            "$sbr",
            "solana ecosystem",
            "solana season",
            "solana summer",
        ],
        "bitcoin": ["bitcoin", "btc", "$btc", "satoshi", "halving", "bitcoin etf"],
        "ethereum": ["ethereum", "eth", "$eth", "vitalik", "merge", "ethereum 2.0"],
        "defi": ["defi", "yield", "apy", "liquidity", "swap", "amm", "dex", "lending"],
        "nft": ["nft", "opensea", "floor", "mint", "collection", "art", "gaming"],
        "meme": ["meme", "dog", "cat", "pepe", "shib", "doge", "bonk", "wojak"],
        "airdrop": ["airdrop", "claim", "free", "drop", "eligible", "whitelist"],
        "scam": ["rug", "scam", "honeypot", "fake", "ponzi", "pyramid"],
        "pump": ["pump", "moon", "bull", "rocket", "🚀", "mooning", "pumping"],
        "trading": [
            "trade",
            "chart",
            "technical",
            "analysis",
            "ta",
            "support",
            "resistance",
        ],
        "news": [
            "news",
            "announcement",
            "update",
            "release",
            "partnership",
            "adoption",
        ],
    }
