name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest -q
      - name: Run dry digest (mock env)
        env:
          OPENROUTER_API_KEY: dummy
        run: |
          python -m storage.db stats || true
