name: Daily Degen Digest

on:
  schedule:
    # 10:00 AM EST = 15:00 UTC (adjust as needed)
    - cron:  '0 15 * * *'
  workflow_dispatch:

jobs:
  build-digest:
    runs-on: ubuntu-latest

    env:
      APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_SESSION: degen_digest
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      PDF_EMOJI_FONT: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y texlive-luatex fonts-noto-color-emoji

      - name: Run scrapers & build digest
        run: |
          python -m scrapers.twitter_apify
          python -m scrapers.reddit_rss
          python -m scrapers.coingecko_gainers
          python -m scrapers.telegram_telethon || echo "telegram optional"
          python main.py
          python scrapers/twitter_metrics_refresh.py
          python processor/virality_train.py

      - name: Commit updated digest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update daily digest [skip ci]"
          branch: main
          push_options: '--force' 